
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'stableyield-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/api/metrics'
    
  - job_name: 'stableyield-system'
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
